name: Azure CI/CD Pipeline


on:

  push:

    branches:

      - master

jobs:

  validate:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code

        uses: actions/checkout@v4


      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: 20


      - name: Install Dependencies

        run: npm install


      - name: Check Syntax

        run: node server.js


  deploy:

    needs: validate

    runs-on: ubuntu-latest


    steps:

      - name: Deploy To Azure VM

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          password: ${{ secrets.PASSWORD }}


          script: |

            cd NodeJS-CRUD

            git pull origin main

            npm install

            pm2 restart app
