name: Azure CI/CD Pipeline


on:

  push:

    branches:

      - master


jobs:

  validate:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code

        uses: actions/checkout@v4


      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: 20


      - name: Install Dependencies

        run: npm install


      - name: Validate package.json

        run: |

          node -e "require('./package.json')"


      - name: Check .env File

        run: |

          if [ ! -f .env ]; then

            echo ".env file missing"

            exit 1

          fi


      - name: Check Required Environment Variables

        run: |

          grep PORT .env || exit 1

          grep JWT_SECRET .env || exit 1


      - name: Syntax Validation

        run: node --check server.js


  deploy:

    needs: validate

    runs-on: ubuntu-latest


    steps:

      - name: Deploy To Azure VM

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          password: ${{ secrets.PASSWORD }}


          script: |

            cd NodeJS-CRUD

            git pull origin master

            npm install

            pm2 restart app
